// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9NZnuq6dX1w_59A1jNsNhr4F0qMk3G3o',
    appId: '1:847806480106:web:ba8c2cffbe85c5e948a193',
    messagingSenderId: '847806480106',
    projectId: 'doancuoiky-test2',
    authDomain: 'doancuoiky-test2.firebaseapp.com',
    databaseURL: 'https://doancuoiky-test2-default-rtdb.firebaseio.com',
    storageBucket: 'doancuoiky-test2.firebasestorage.app',
    measurementId: 'G-G342G6Y0VD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB68IWdLbj1rewMtTHqG0cAfvC7FD3fUAQ',
    appId: '1:847806480106:android:a5be41995bccb45748a193',
    messagingSenderId: '847806480106',
    projectId: 'doancuoiky-test2',
    databaseURL: 'https://doancuoiky-test2-default-rtdb.firebaseio.com',
    storageBucket: 'doancuoiky-test2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcPsN-ghcWsup-O86rRyic2ZiyJf2THzo',
    appId: '1:847806480106:ios:5e97efcb935c9d4748a193',
    messagingSenderId: '847806480106',
    projectId: 'doancuoiky-test2',
    storageBucket: 'doancuoiky-test2.firebasestorage.app',
    iosBundleId: 'com.example.doancuoikyTest2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcPsN-ghcWsup-O86rRyic2ZiyJf2THzo',
    appId: '1:847806480106:ios:5e97efcb935c9d4748a193',
    messagingSenderId: '847806480106',
    projectId: 'doancuoiky-test2',
    storageBucket: 'doancuoiky-test2.firebasestorage.app',
    iosBundleId: 'com.example.doancuoikyTest2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9NZnuq6dX1w_59A1jNsNhr4F0qMk3G3o',
    appId: '1:847806480106:web:32b593b2c2fa9f1448a193',
    messagingSenderId: '847806480106',
    projectId: 'doancuoiky-test2',
    authDomain: 'doancuoiky-test2.firebaseapp.com',
    storageBucket: 'doancuoiky-test2.firebasestorage.app',
    measurementId: 'G-08GJZ14E19',
  );
}